feat: linux musl static bins / windows aarch64
- create linux executables linked statically to musl
  - drop gnu (glibc) target, executable will work on alpine & glibc based distros (debian etc)
- create windows aarch64 target
  - required update to Cargo.lock to update ring to v0.17 due to build failures on v0.16
- refactor release script & workflow to match pact-reference
  - builds on pull request to master/main branch, in debug mode
- add Docker automated pipeline during release
  - publish multi-arch amd64/arm64
  - publish to DockerHub
  - publish to GitHub container registry

Related epics

- musl all the things
  - https://github.com/pact-foundation/devrel/issues/30
- publish to github container registry
  - https://github.com/pact-foundation/devrel/issues/29

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,14 +1,21 @@
-ARG ARCH=
 FROM debian:11-slim as builder
-ARG VERSION=0.5.0
-ARG BIN_ARCH=x86_64
+ARG TARGETARCH
+ARG VERSION=0.5.3
 
 RUN apt-get update && apt-get install -y wget
-RUN wget -O pact-stub-server.gz https://github.com/uglyog/pact-stub-server/releases/download/v${VERSION}/pact-stub-server-linux-${BIN_ARCH}.gz
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        BIN_ARCH="x86_64"; \
+    elif [ "$TARGETARCH" = "arm64" ]; then \
+        BIN_ARCH="aarch64"; \
+    else \
+        echo "Invalid TARGET_ARCH"; \
+        exit 1; \
+    fi \
+    && wget -O pact-stub-server.gz https://github.com/pact-foundation/pact-stub-server/releases/download/v${VERSION}/pact-stub-server-linux-${BIN_ARCH}.gz
 RUN gunzip pact-stub-server.gz
 RUN chmod +x pact-stub-server
 
-FROM ${ARCH}debian:11-slim
+FROM --platform=linux/${TARGETARCH} debian:11-slim
 WORKDIR /app
 COPY --from=builder /pact-stub-server /app/
 EXPOSE 8080
